### ISSUE TITLE
Ontwerp website maken

### ISSUE THREAD

**Issue by RobbeDeW** [vives-project-xp/InteractiveCorridor#44]
Een ontwerp maken voor de website. Dit wordt best eerst op papier in klad gedaan. 
- Hoe ziet de website er uit
- Interactie met gebruiker en leds
- Pagina effecten, interactie,

**Comment by SimonStnn** [comment]
Ontwerp kan met figma gemaakt worden. Die kunnen opgeslaan worden als .fig bestanden.
