### ISSUE TITLE
Mail Sam Baldewijns

### ISSUE THREAD

**Issue by NielsDenoo** [vives-project-xp/InteractiveCorridor#5]
Mail sturen naar Sam Baldewijns voor mogelijkheden elektriciteit voor ledstrips (eerst mail sturen naar meneer Leroy voor goedkeuring mail)

**Comment by RobbeDeW** [comment]
Mail naar project begeleider verstuurt om te weten of het een goede mail was en we mogen afspreken met Sam.

**Comment by RobbeDeW** [comment]
Mail naar Sam is verzonden.

**Comment by RobbeDeW** [comment]
Er is een datum vastgelegd om af te spreken met Sam.
