### ISSUE TITLE
Testen 24V Ledstip

### ISSUE THREAD

**Issue by RobbeDeW** [vives-project-xp/InteractiveCorridor#60]
-Er worden metingen gedaan met deze ledstip
-Er wordt getest of de ledstip goed werkt

**Comment by RobbeDeW** [comment]
Ledstip werkt zonder level shifter maar als we een level shifter gebruiken die in school aanwezig was werkt de ledstip niet meer.

**Comment by imawizzard** [comment]
Met onze eigen levelshifter werken de ledstrips perfect. Er zijn geen verstoringen meer doordat de data nu op 5V wordt gestuurd.
